apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
data:
  s3.conf: {{print "[global]\n"
                  "repo1-s3-key=" .Values.db.aws.key "\n"
                  "repo1-s3-key-secret=" .Values.db.aws.key_secret "\n"
                  | b64enc}}

